### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by util-you-com** [DuHouAn/Java#3]
您好！我想问一下https://duhouan.github.io/Java/#/AimForOffer/1_%E6%95%B0%E7%BB%84，这个链接中的第一个解决方法是不是有点问题，当二维数组不是均匀数组时，是不是不对了？比如：[[1,2,2], [4,5], [7,8,9]];因为第一个 else 中只改变了 i 的值，j不作改变，这样就可能会出现下标越界的exception。

**Comment by DuHouAn** [comment]
不好意思，这一段时间忙着找工作，没太关注这里。您说的也对，但是题目中每个一维数组的长度都相同的。

**Comment by util-you-com** [comment]
哦哦，这样啊，谢谢。我也是刚入职一家公司
